#!/bin/sh
#
# Toggle webcam for streaming.
#
# Requires: mpv

cam_dev=av://v4l2:/dev/video0

pkill -f /dev/video0 || mpv \
    --autofit=25% \
    --config=no \
    --geometry=-10-10 \
    --input-default-bindings=no \
    --osc=no \
    --profile=low-latency \
    --untimed \
    --vf=hflip \
    --x11-name=mpv-webcam "$cam_dev" # >/dev/null 2>&1
