#!/bin/sh

microphone="alsa_input.pci-0000_00_1b.0.analog-stereo"
speakers="alsa_output.pci-0000_00_1b.0.analog-stereo"

printf '%s\n' "Setting up echo cancellation"
pactl load-module module-echo-cancel use_master_format=1 aec_method=webrtc \
      aec_args="analog_gain_control=0\\ digital_gain_control=1\\ experimental_agc=1\\ noise_suppression=1\\ voice_detection=1\\ extended_filter=1" \
      source_master="$microphone" source_name=src_ec  source_properties=device.description=src_ec \
      sink_master="$speakers"     sink_name=sink_main sink_properties=device.description=sink_main

printf '%s\n' "Creating virtual output devices"
pactl load-module module-null-sink sink_name=sink_fx  sink_properties=device.description=sink_fx
pactl load-module module-null-sink sink_name=sink_mix sink_properties=device.description=sink_mix

printf '%s\n' "Creating remaps"
pactl load-module module-remap-source master=sink_mix.monitor \
      source_name=src_main source_properties="device.description=src_main"

printf '%s\n' "Setting default devices"
pactl set-default-source src_main
pactl set-default-sink   sink_main

printf '%s\n' "Creating loopbacks"
pactl load-module module-loopback latency_msec=60 adjust_time=6 source=src_ec          sink=sink_mix
pactl load-module module-loopback latency_msec=60 adjust_time=6 source=sink_fx.monitor sink=sink_mix
pactl load-module module-loopback latency_msec=60 adjust_time=6 source=sink_fx.monitor sink=sink_main
